sudo: false
language: go
git:
  depth: 1
install: go get -v github.com/gohugoio/hugo
script:
  ‐ hugo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: source
  local_dir: public
  repo: yufulou/yufulou.github.io
  fqdn: yufulou.github.io
  target_branch: master
  email: yufulou@qq.com
  name: yufulou
