sudo: false
language: go

env:
  global:
    - CACHE_NAME=${TRAVIS_ARCH}
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
    - HUGO_BUILD_TAGS=extended
    - PATH=$PATH:$GOPATH/bin

go:
  - "1.12.13"
  - "1.13.4"
  - master

git:
  depth: 1
install:
  - go get -v github.com/gohugoio/hugo
script:
  ‐ hugo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: source
  local_dir: public
  repo: yufulou/yufulou.github.io
  fqdn: yufulou.github.io
  target_branch: master
  email: yufulou@qq.com
  name: yufulou
